import time
from typing import Dict, Any, Optional
from ai_router.classifier import ClassificationResult
from ai_router.n8n_pipeline import PrepResult
from ai_router.security_guard import SecurityGuard
from ai_router.engines.base import ExecutionResult, EngineStatus


class MockServices:
    """
    Offline Simulation & Demonstration Engine.
    Enables zero-credential testing, instant demo runs, and offline development.
    """

    @classmethod
    def mock_classification(cls, prompt: str, force_engine: Optional[str] = None) -> ClassificationResult:
        lower = prompt.lower()
        if "stripe" in lower or "auth" in lower or "integrate" in lower:
            intent = "PREP_AND_EXECUTE"
            score = 3
        elif "explain" in lower or "info" in lower:
            intent = "RESEARCH_ONLY"
            score = 2
        else:
            intent = "EXECUTE_ONLY"
            score = 1

        engine = force_engine or ("gemini" if "analyze" in lower else "claude")

        return ClassificationResult(
            intent=intent,
            complexity_score=score,
            suggested_engine=engine,
            confidence=0.98,
            reasoning="Mock Classifier simulation",
            is_fast_path=intent == "EXECUTE_ONLY",
            evaluation_duration_ms=4.2,
        )

    @classmethod
    def mock_n8n_prep(cls, prompt: str) -> PrepResult:
        time.sleep(0.3)  # Fast simulated latency
        mock_md = (
            f"### Official Documentation & Schema for: {prompt}\n\n"
            f"```typescript\n"
            f"// Standard Verified Integration Pattern\n"
            f"export async function handleWebhook(payload: Buffer, sig: string) {{\n"
            f"  const event = stripe.webhooks.constructEvent(payload, sig, process.env.STRIPE_WEBHOOK_SECRET!);\n"
            f"  if (event.type === 'checkout.session.completed') {{\n"
            f"    const session = event.data.object;\n"
            f"    // Fulfill customer purchase\n"
            f"  }}\n"
            f"  return {{ received: true }};\n"
            f"}}\n"
            f"```\n"
            f"- Endpoint: `POST /api/webhooks/stripe`\n"
            f"- Auth: Raw body HMAC verification required."
        )

        sanitized = SecurityGuard.sanitize_untrusted_research(mock_md, source_url="https://docs.stripe.com/webhooks")

        return PrepResult(
            success=True,
            sanitized_context=sanitized,
            source_url="https://docs.stripe.com/webhooks",
            duration_ms=310.0,
            circuit_tripped=False,
            fallback_used="mock_engine",
        )

    @classmethod
    def mock_execution(cls, engine: str, prompt: str, context: Optional[str] = None) -> ExecutionResult:
        time.sleep(0.4)
        mock_output = (
            f"// Code Generated by {engine.upper()} Engine\n"
            f"// Objective: {prompt}\n\n"
            f"export function executeTask() {{\n"
            f"  console.log('Task executed successfully using reference context.');\n"
            f"  return true;\n"
            f"}}\n"
        )

        return ExecutionResult(
            status=EngineStatus.SUCCESS,
            engine_name=engine,
            output_text=mock_output,
            exit_code=0,
            duration_ms=420.0,
            input_tokens=180,
            output_tokens=65,
            cost_usd=0.0004,
            gateway_metadata={"cache_status": "HIT", "latency_ms": 22.0},
        )
