import time
from typing import Dict, Any, Optional
from ai_router.classifier import ClassificationResult
from ai_router.n8n_pipeline import PrepResult
from ai_router.security_guard import SecurityGuard
from ai_router.engines.base import ExecutionResult, EngineStatus
from ai_router.config import get_config


class MockServices:
    """
    Offline Simulation & Demonstration Engine.
    Enables zero-credential testing, instant demo runs, and offline development.
    """

    @classmethod
    def mock_classification(cls, prompt: str, force_engine: Optional[str] = None) -> ClassificationResult:
        config = get_config()
        lower = prompt.lower()
        engine = force_engine or ("gemini" if "analyze" in lower else "claude")

        def default_model(eng: str, heavy: bool) -> str:
            if eng == "gemini":
                return config.gemini_exec_model if heavy else config.gemini_model
            if eng == "codex":
                return config.codex_model
            return config.claude_model if heavy else "claude-haiku-4-5-20251001"

        if "stripe" in lower or "auth" in lower or "integrate" in lower:
            intent = "PREP_AND_EXECUTE"
            score = 4
            model = default_model(engine, heavy=True)
            effort = 5
        elif "explain" in lower or "info" in lower:
            intent = "RESEARCH_ONLY"
            score = 2
            model = default_model(engine, heavy=False)
            effort = 2
        else:
            intent = "EXECUTE_ONLY"
            score = 1
            model = default_model(engine, heavy=False)
            effort = 1

        if engine == "claude" and intent != "EXECUTE_ONLY":
            model = config.claude_model
            effort = 5

        return ClassificationResult(
            intent=intent,
            complexity_score=score,
            suggested_engine=engine,
            suggested_model=model,
            effort_level=effort,
            confidence=0.98,
            reasoning=f"Mock Classifier: Identified {model} with effort {effort}/5",
            is_fast_path=intent == "EXECUTE_ONLY",
            evaluation_duration_ms=4.2,
        )

    @classmethod
    def mock_n8n_prep(cls, prompt: str) -> PrepResult:
        time.sleep(0.3)
        mock_md = (
            f"### Official Documentation & Schema for: {prompt}\n\n"
            f"```typescript\n"
            f"// Standard Verified Integration Pattern\n"
            f"export async function handleWebhook(payload: Buffer, sig: string) {{\n"
            f"  const event = stripe.webhooks.constructEvent(payload, sig, process.env.STRIPE_WEBHOOK_SECRET!);\n"
            f"  if (event.type === 'checkout.session.completed') {{\n"
            f"    const session = event.data.object;\n"
            f"    // Fulfill customer purchase\n"
            f"  }}\n"
            f"  return {{ received: true }};\n"
            f"}}\n"
            f"```\n"
            f"- Endpoint: `POST /api/webhooks/stripe`\n"
            f"- Auth: Raw body HMAC verification required."
        )

        sanitized = SecurityGuard.sanitize_untrusted_research(mock_md, source_url="https://docs.stripe.com/webhooks")

        return PrepResult(
            success=True,
            sanitized_context=sanitized,
            source_url="https://docs.stripe.com/webhooks",
            duration_ms=310.0,
            circuit_tripped=False,
            fallback_used="mock_engine",
        )

    @classmethod
    def mock_execution(cls, engine: str, prompt: str, context: Optional[str] = None, model: str = "claude-opus-5", effort: int = 5) -> ExecutionResult:
        time.sleep(0.4)
        mock_output = (
            f"// Code Generated by {engine.upper()} ({model}) [Effort {effort}/5 Extra]\n"
            f"// Objective: {prompt}\n\n"
            f"export function executeTask() {{\n"
            f"  console.log('Task verified with exhaustive reasoning.');\n"
            f"  return true;\n"
            f"}}\n"
        )

        return ExecutionResult(
            status=EngineStatus.SUCCESS,
            engine_name=engine,
            output_text=mock_output,
            exit_code=0,
            duration_ms=420.0,
            input_tokens=180,
            output_tokens=65,
            cost_usd=0.0004,
            gateway_metadata={"cache_status": "HIT", "latency_ms": 22.0},
        )
